"""content approvals and durable simulation runs"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002_content_runs"
down_revision = "0001_foundation"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("consumer", sa.String(length=200), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "consumer", "event_id"),
    )
    op.create_table(
        "service_heartbeats",
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("instance_id", sa.String(length=36), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("service", "instance_id"),
    )
    op.create_table(
        "content_revisions",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("entity_kind", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.String(length=36), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id"],
            ["projects.tenant_id", "projects.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "project_id", "entity_kind", "revision"),
    )
    op.create_table(
        "production_snapshots",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id"],
            ["projects.tenant_id", "projects.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    op.create_table(
        "approvals",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("revision_id", sa.String(length=36), nullable=False),
        sa.Column("subject_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id"],
            ["projects.tenant_id", "projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "revision_id"],
            ["content_revisions.tenant_id", "content_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    op.create_index(
        "ix_approvals_revision",
        "approvals",
        ["tenant_id", "revision_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "content_heads",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("entity_kind", sa.String(length=20), nullable=False),
        sa.Column("revision_id", sa.String(length=36), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id"],
            ["projects.tenant_id", "projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "revision_id"],
            ["content_revisions.tenant_id", "content_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "project_id", "entity_kind"),
    )
    op.create_table(
        "production_runs",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("execution_mode", sa.String(length=20), nullable=False),
        sa.Column("workflow_id", sa.String(length=200), nullable=False),
        sa.Column("temporal_run_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("pause_requested", sa.Boolean(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("control_seq", sa.Integer(), nullable=False),
        sa.Column("consumed_control_seq", sa.Integer(), nullable=False),
        sa.Column("completed_shots", sa.Integer(), nullable=False),
        sa.Column("total_shots", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("start_actor_id", sa.String(length=36), nullable=False),
        sa.Column("start_command_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id"],
            ["projects.tenant_id", "projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "snapshot_id"],
            ["production_snapshots.tenant_id", "production_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(
        "ix_runs_project",
        "production_runs",
        ["tenant_id", "project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "outbox",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "id"],
            ["project_events.tenant_id", "project_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "run_id"],
            ["production_runs.tenant_id", "production_runs.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    op.create_index("ix_outbox_delivery", "outbox", ["status", "available_at"], unique=False)
    op.create_table(
        "run_controls",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_id", "command_id"],
            ["commands.tenant_id", "commands.actor_id", "commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "run_id"],
            ["production_runs.tenant_id", "production_runs.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "run_id", "seq"),
    )
    op.create_table(
        "simulation_steps",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=200), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "run_id"],
            ["production_runs.tenant_id", "production_runs.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "run_id", "operation_id"),
    )
    op.add_column(
        "project_events",
        sa.Column("subject_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "project_events",
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.execute("""
        CREATE FUNCTION video_reject_immutable_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'immutable record: %', TG_TABLE_NAME;
        END;
        $$
    """)
    for table in ("content_revisions", "approvals", "production_snapshots", "simulation_steps"):
        op.execute(
            f"CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION video_reject_immutable_change()"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_events", "payload")
    op.drop_column("project_events", "subject_ref")
    op.drop_table("simulation_steps")
    op.drop_table("run_controls")
    op.drop_index("ix_outbox_delivery", table_name="outbox")
    op.drop_table("outbox")
    op.drop_index("ix_runs_project", table_name="production_runs")
    op.drop_table("production_runs")
    op.drop_table("content_heads")
    op.drop_index("ix_approvals_revision", table_name="approvals")
    op.drop_table("approvals")
    op.drop_table("production_snapshots")
    op.drop_table("content_revisions")
    op.drop_table("service_heartbeats")
    op.drop_table("inbox")
    op.execute("DROP FUNCTION video_reject_immutable_change()")
    # ### end Alembic commands ###
